languageCode = "en-us"
title = "Program Exit Assessment"
relativeURLs = true

[[menu.main]]
weight = 1
name = "Initiation"
url = "/process"

[[menu.main]]
weight = 2
name = "Construction"
url = "/requirements"

[[menu.main]]
weight = 3
name = "Release"
url = "/deployment"
